Internal Server Error: /admin/DepartmentApp/department/
Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "DepartmentApp_department" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "DepartmentApp_department"
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2024, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 867, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/paginator.py", line 110, in count
    return c()
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "DepartmentApp_department" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "DepartmentApp_department"
                                          ^

"GET /admin/DepartmentApp/department/ HTTP/1.1" 500 188222
Internal Server Error: /admin/UsersApp/userprofile/
Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column UsersApp_userprofile.email does not exist
LINE 1: ..."user_id", "UsersApp_userprofile"."phone_number", "UsersApp_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2163, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column UsersApp_userprofile.email does not exist
LINE 1: ..."user_id", "UsersApp_userprofile"."phone_number", "UsersApp_...
                                                             ^

"GET /admin/UsersApp/userprofile/ HTTP/1.1" 500 171289
Internal Server Error: /admin/SurveyApp/answer/
Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column SurveyApp_answer.answer_text does not exist
LINE 1: ...."response_id", "SurveyApp_answer"."question_id", "SurveyApp...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2163, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column SurveyApp_answer.answer_text does not exist
LINE 1: ...."response_id", "SurveyApp_answer"."question_id", "SurveyApp...
                                                             ^

"GET /admin/SurveyApp/answer/ HTTP/1.1" 500 165779
Internal Server Error: /admin/SurveyApp/survey/
Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column SurveyApp_survey.site_id does not exist
LINE 1: ...urvey"."title", "SurveyApp_survey"."description", "SurveyApp...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2163, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column SurveyApp_survey.site_id does not exist
LINE 1: ...urvey"."title", "SurveyApp_survey"."description", "SurveyApp...
                                                             ^

"GET /admin/SurveyApp/survey/ HTTP/1.1" 500 167176
Internal Server Error: /admin/SurveyApp/department/
Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "SurveyApp_department" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "SurveyApp_department"
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2024, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 867, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/paginator.py", line 110, in count
    return c()
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "SurveyApp_department" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "SurveyApp_department"
                                          ^

"GET /admin/SurveyApp/department/ HTTP/1.1" 500 187559
Internal Server Error: /admin/SurveyApp/answer/
Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column SurveyApp_answer.answer_text does not exist
LINE 1: ...."response_id", "SurveyApp_answer"."question_id", "SurveyApp...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2163, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column SurveyApp_answer.answer_text does not exist
LINE 1: ...."response_id", "SurveyApp_answer"."question_id", "SurveyApp...
                                                             ^

"GET /admin/SurveyApp/answer/ HTTP/1.1" 500 181901
Internal Server Error: /admin/SurveyApp/survey/
Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column SurveyApp_survey.site_id does not exist
LINE 1: ...urvey"."title", "SurveyApp_survey"."description", "SurveyApp...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2163, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column SurveyApp_survey.site_id does not exist
LINE 1: ...urvey"."title", "SurveyApp_survey"."description", "SurveyApp...
                                                             ^

"GET /admin/SurveyApp/survey/ HTTP/1.1" 500 167184
Internal Server Error: /admin/SurveyApp/department/
Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "SurveyApp_department" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "SurveyApp_department"
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2024, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 867, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/contrib/admin/views/main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/paginator.py", line 110, in count
    return c()
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "SurveyApp_department" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "SurveyApp_department"
                                          ^

"GET /admin/SurveyApp/department/ HTTP/1.1" 500 187559
Internal Server Error: /survey/api/update-department/2
Traceback (most recent call last):
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/md.zahedhasanrabbi/Downloads/Development/DjangoBackend/BackendSurveyCore/env/lib/python3.13/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
    ...<9 lines>...
    )
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/survey/api/update-department/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST //survey/api/update-department/2 HTTP/1.1" 500 69355
